[package]
name = "pawnyowl"
edition.workspace = true
version.workspace = true
repository.workspace = true
license.workspace = true

[dependencies]
pawnyowl_board = { path = "../board", version = "0.1.0" }
anyhow = "1.0.97"
scopeguard = "1.2.0"
