[workspace]
members = [
    "base",
    "board",
    "eval",
    "tools/learner",
    "pawnyowl",
]
resolver = "2"

[workspace.package]
edition = "2024"
version = "0.1.0"
repository = "https://github.com/PawnyOwl/PawnyOwl"
license = "MIT"
